-- alter table addressbinding drop foreign key FKAEDF781176B58A6;
-- alter table addressbinding drop foreign key FKAEDF781134BD9F98;
-- alter table clientorder drop foreign key FKF6863A63280FA25E;
-- alter table clientorder drop foreign key FKF6863A63D9722EEA;
-- alter table clientorder drop foreign key FKF6863A6334BD9F98;
-- alter table contactbinding drop foreign key FK7B6AA6651AA68FE;
-- alter table contactbinding drop foreign key FK7B6AA66534BD9F98;
-- alter table product drop foreign key FKED8DCCEF7B855F24;
-- alter table product drop foreign key FKED8DCCEF34BB837C;
-- alter table rating drop foreign key FKC815B19D6B57BA9C;
-- alter table rating drop foreign key FKC815B19D34BD9F98;
drop table if exists address;
drop table if exists addressbinding;
drop table if exists category;
drop table if exists clientorder;
drop table if exists contact;
drop table if exists contactbinding;
drop table if exists delivery;
drop table if exists paymenttype;
drop table if exists product;
drop table if exists rating;
drop table if exists segment;
drop table if exists sign;
drop table if exists user;
drop table if exists IdentityGenerator;
create table address (id integer not null, city varchar(255), street varchar(255), zip varchar(255), primary key (id));
create table addressbinding (id integer not null, deliveryhome bit, address integer not null, user integer not null, primary key (id));
create table category (id integer not null, name varchar(255), primary key (id));
create table clientorder (id integer not null, date datetime, delivery integer not null, paymenttype integer not null, user integer not null, primary key (id));
create table contact (id integer not null, name varchar(255), primary key (id));
create table contactbinding (id integer not null, contact integer not null, user integer not null, primary key (id));
create table delivery (id integer not null, name varchar(255), primary key (id));
create table paymenttype (id integer not null, name varchar(255), primary key (id));
create table product (id integer not null, count integer, name varchar(255), price double precision, sex integer, segment integer not null, sign integer not null, primary key (id));
create table rating (id integer not null, value integer, product integer not null, user integer not null, primary key (id));
create table segment (id integer not null, name varchar(255), primary key (id));
create table sign (id integer not null, name varchar(255), primary key (id));
create table user (id integer not null, login varchar(255), name varchar(255), pass varchar(255), privilegy integer, surname varchar(255), primary key (id));
alter table addressbinding add index FKAEDF781176B58A6 (address), add constraint FKAEDF781176B58A6 foreign key (address) references address (id);
alter table addressbinding add index FKAEDF781134BD9F98 (user), add constraint FKAEDF781134BD9F98 foreign key (user) references user (id);
alter table clientorder add index FKF6863A63280FA25E (paymenttype), add constraint FKF6863A63280FA25E foreign key (paymenttype) references paymenttype (id);
alter table clientorder add index FKF6863A63D9722EEA (delivery), add constraint FKF6863A63D9722EEA foreign key (delivery) references delivery (id);
alter table clientorder add index FKF6863A6334BD9F98 (user), add constraint FKF6863A6334BD9F98 foreign key (user) references user (id);
alter table contactbinding add index FK7B6AA6651AA68FE (contact), add constraint FK7B6AA6651AA68FE foreign key (contact) references contact (id);
alter table contactbinding add index FK7B6AA66534BD9F98 (user), add constraint FK7B6AA66534BD9F98 foreign key (user) references user (id);
alter table product add index FKED8DCCEF7B855F24 (segment), add constraint FKED8DCCEF7B855F24 foreign key (segment) references segment (id);
alter table product add index FKED8DCCEF34BB837C (sign), add constraint FKED8DCCEF34BB837C foreign key (sign) references sign (id);
alter table rating add index FKC815B19D6B57BA9C (product), add constraint FKC815B19D6B57BA9C foreign key (product) references product (id);
alter table rating add index FKC815B19D34BD9F98 (user), add constraint FKC815B19D34BD9F98 foreign key (user) references user (id);
create table IdentityGenerator ( sequence_name varchar(100),  next_hi_value integer );
